CatSim/Controllers/CatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BLL;
using AutoMapper;
using CatSim.Models;

namespace CatSim.Controllers
{
    public class CatController : Controller
    {
        private ICatLogic catLog;
        private ISessionAccessor sessionAccess;

        public CatController(ICatLogic data, ISessionAccessor sessionData)
        {
            catLog = data;
            sessionAccess = sessionData;
        }

        // GET: Cat
        public ActionResult Index()
        {
            return View();
        }

        // GET: Cat
        public ActionResult DisplayCats()
        {
            List<CatSM> kitties = catLog.ReadCats();
            return View(kitties);
        }

        // GET: Cat/Details/5
        public ActionResult Details(int id)
        {
            CatSM meow = catLog.GetCatByID(id);
            return View(meow);
        }

        // GET: Cat/Create
        public ActionResult Create()
        {
            CatSim.Models.AllCatVM meow = new AllCatVM();
            return View();
        }

        // POST: Cat/Create
        [HttpPost]
        public ActionResult Create(AllCatVM meow)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    catLog.CreateCat(Mapper.Map<AllCatSM>(meow));
                    return RedirectToAction("DisplayCats");
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Cat/Edit/5
        public ActionResult Edit(int id)
        {
            CatVM meow = Mapper.Map<CatVM>(catLog.GetCatByID(id));
            return View(meow);
        }

        // POST: Cat/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, CatVM meow)
        {
            try
            {
                catLog.UpdateCat(Mapper.Map<CatSM>(meow));
                return RedirectToAction("DisplayCats");
            }
            catch
            {
                return View();
            }
        }

        // GET: Cat/Delete/5
        public ActionResult Delete(int id)
        {
            CatSM meow = catLog.GetCatByID(id);
            return View(meow);
        }

        // POST: Cat/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, AllCatVM meow)
        {
            try
            {
                catLog.DeleteCat(Mapper.Map<AllCatSM>(meow));
                return RedirectToAction("DisplayCats");
            }
            catch
            {
                return View();
            }
        }
    }
}

CatSim/Views/Cat/Create.cshtml
@model CatSim.Models.AllCatVM

@{

    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Session["UserRole"] == null)
{
    Response.Redirect(Url.Action("Index", "Home"));
}
else if (Session["UserRole"].ToString() == "User")
{
    Response.Redirect(Url.Action("Index", "Home"));
}
else
{
    using (Html.BeginForm("Create", "Cat", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <h5>What's the new cat's name?</h5>
            <div class="form-group">
                @Html.LabelFor(model => model.Meow.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Meow.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Meow.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <h5>Tell us about them...</h5>
            <div class="form-group">
                @Html.LabelFor(model => model.Bio.Bio, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Bio.Bio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Bio.Bio, "", new { @class = "text-danger" })
                </div>
            </div>

            <h5>Their stats... Remember, the higher their stat, the harder it is to get an ending other than generic. [1 - 10]</h5>
            <div class="form-group">
                @Html.LabelFor(model => model.Stats.Friendliness, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Stats.Friendliness, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Stats.Friendliness, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Stats.Aggressiveness, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Stats.Aggressiveness, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Stats.Aggressiveness, "", new { @class = "text-danger" })
                </div>
            </div>

            <h5>Their interaction endings; fight, play, and generic. Remember! There's no right way to end a scenario with a cat. What do you think should happen?</h5>
            <div class="form-group">
                @Html.LabelFor(model => model.Ending.Fight, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ending.Fight, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ending.Fight, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Ending.Play, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ending.Play, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ending.Play, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Ending.Generic, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Ending.Generic, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Ending.Generic, "", new { @class = "text-danger" })
                </div>
            </div>

            <h5>Do you have a picture of the cat? Upload it here!</h5> <p>((this is where I'd like to add a feature to upload and save pictures from an outside source))</p>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
}

<div>
    @Html.ActionLink("Back to List", "DisplayCats")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CatSim/Views/Cat/Delete.cshtml
@model BLL.CatSM

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Session["UserRole"] == null)
{
    Response.Redirect(Url.Action("Index", "Home"));
}
else if (Session["UserRole"].ToString() != "Admin")
{
    Response.Redirect(Url.Action("Index", "Home"));
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CatVM</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "DisplayCats")
        </div>
    }
</div>

CatSim/Views/Cat/Details.cshtml
@model BLL.CatSM

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Session["UserRole"] == null)
{
    Response.Redirect(Url.Action("Index", "Home"));
}

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>
</div>

@if (Session["UserRole"].ToString() != "User")
{
    <p>
        @Html.ActionLink("Edit", "Edit", new { ID = Model.ID }) |
        @Html.ActionLink("Back to List", "DisplayCats")
    </p>
}
else
{
    <p>
        @Html.ActionLink("Back to List", "DisplayCats")
    </p>
}

CatSim/Views/Cat/DisplayCats.cshtml
@model IEnumerable<BLL.CatSM>

@{
    ViewBag.Title = "DisplayCats";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Session["UserRole"] == null)
{
    Response.Redirect(Url.Action("Index", "Home"));
}

<h4>View the Cats</h4>

<p>
    @if (Session["UserRole"].ToString() != "User")
    {
        @Html.ActionLink("Create New", "Create")
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        @if (Session["UserRole"].ToString() == "Admin")
        {
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        }
        else
        {
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ID })
            </td>
        }
    </tr>
}

</table>

CatSim/Views/Cat/Edit.cshtml
@model CatSim.Models.CatVM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Session["UserRole"] == null)
{
    Response.Redirect(Url.Action("Index", "Home"));
}
else if (Session["UserRole"].ToString() == "User")
{
    Response.Redirect(Url.Action("Index", "Home"));
}
else
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ID)
            @Html.HiddenFor(model => model.StatsID)
            @Html.HiddenFor(model => model.CatInfoID)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
}

<div>
    @Html.ActionLink("Back to List", "DisplayCats")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}